### ISSUE TITLE
Represent within-task state in URL

### ISSUE THREAD

**Issue by gertvv** [drugis/mcda-elicitation-web#27]
Within-task state should be serialized to the URL so that the back-button doesn't break and users can link to specific steps.

**Comment by gertvv** [comment]
Why did you close this?

**Comment by joelkuiper** [comment]
It was a bit of an effort/worth trade-off. If we truly want this we need to
pass the entire state as a query param (and somehow merge this with remote
and local storage and the hidden state in the wizard steps). This would
mean major rewrites of the application for a rather obscure feature.


On Thu, Jan 22, 2015 at 1:58 PM, Gert van Valkenhoef <
notifications@github.com> wrote:

> Why did you close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drugis/mcda-elicitation-web/issues/27#issuecomment-71016477>
> .
>



-- 
www.joelkuiper.eu
