### ISSUE TITLE
Replace jquery-slider with something nicer (and touch friendly?)

### ISSUE THREAD

**Issue by gertvv** [drugis/mcda-elicitation-web#56]
For example [nstslider](http://lokku.github.io/jquery-nstslider/) could be the thing.

**Comment by joelkuiper** [comment]
:+1:

**Comment by gertvv** [comment]
Or... https://github.com/Venturocket/angular-slider

**Comment by joelkuiper** [comment]
nstslider doesn't really work well with angular and/or small floating point numbers (and lacks the calculate that the current slider does support to fake it)

**Comment by joelkuiper** [comment]
After evaluating some additional options I feel we should leave it "as-is" or invest some time in developing something ourselves (not necessarily from scratch, but still)

**Comment by DanielReid** [comment]
Fixed some time ago
